name: CIFF
on:
  push:
    branches: 
      - master
env:
  CFN_STACKNAME: 'infra-permission'
  CFN_TEMPLATE: './cloudformation/service.yaml'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: ${CFN_TEMPLATE}
      - run: find . -type f
      - run: touch 123123123
      - run: find . -type f
      
  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - run: touch aaaaaaaaa
      - run: find . -type f
