name: CI
on:
  push:
    branches: 
      - master
jobs:
  test_and_deployment:
    name: test_and_deployment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - run: python --version
      - run: aws --version
      - run: pip install --upgrade awscli
      - run: aws --version
