name: CI
on:
  push:
    branches: 
      - master
jobs:
  test_and_deployment:
    name: test_and_deployment
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy2', 'pypy3' ]
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!      
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python --version
