name: CI
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Amazon ECS "Deploy Task Definition" Action for GitHub Actions
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.0.0
      with:
        task-definition: task-definition.json
        service: my-service
        cluster: my-cluster
        wait-for-service-stability: true
