name: CIFF
on:
  push:
    branches: 
      - master
      - deploy/test
env:
  CFN_STACKNAME: infra-permission
  CFN_TEMPLATE: ./cloudformation/service.yaml

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v1
      
      #- name: cfn-lint
      #  uses: scottbrenner/cfn-lint-action@master
      #  with:
      #    args: ${CFN_TEMPLATE}
      - run: find . -type f
      - run: touch 123123123
      - run: find . -type f
      
  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - run: touch aaaaaaaaa
      - run: find . -type f
      - run: |
          env|sort

      - uses: rlespinasse/github-slug-action@1.0.1
      - name: Print slug variables
        run: |
                echo ${{ env.GITHUB_REF_SLUG }}
                echo ${{ env.GITHUB_HEAD_REF_SLUG }}
                echo ${{ env.GITHUB_BASE_REF_SLUG }}
